[project]
name = "ContextRAG"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.13"
authors = [{ name = "Sean Brar", email = "hello@seanbrar.com" }]
dependencies = [
    "beautifulsoup4~=4.14.3",
    "chromadb~=1.4.1",
    "click~=8.3.1",
    "gensim~=4.4.0",
    "html2text~=2025.4.15",
    "joblib~=1.5.3",
    "nltk~=3.9.2",
    "openai~=2.15.0",
    "pytest~=9.0.2",
    "python-dotenv~=1.2.1",
    "regex~=2026.1.15",
    "scikit-learn~=1.8.0",
    "tiktoken~=0.12.0",
    "tqdm~=4.67.1",
]

[project.scripts]
contextrag = "contextrag.cli:main"

[tool.poetry]
packages = [{ include = "contextrag", from = "src" }]

[tool.poetry.group.dev.dependencies]
isort = "^7.0.0"
ruff = "^0.14.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
